jobs:
- job: GitVersion
  pool:
    name: SLD Build pool
    #demands: LATEST_DOTNET_VERSION
  variables:
    - name: patch
      value: 0
    - name: counterVar
      value: $[counter(variables['patch'], 1)]
  steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '3.x'
        installationPath: $(Agent.ToolsDirectory)/dotnet

    - script: dotnet tool install --global GitVersion.Tool
      displayName: 'Install GitVersion'

    - script: gitversion /updateassemblyinfo
      displayName: 'Update Version'

next-version: $(counterVar).0
mode: Mainline
