jobs:
- job: GitVersion
  pool:
    name: SLD Build pool
    #demands: LATEST_DOTNET_VERSION
  variables:
    - name: patch
      value: 0
    - name: counterVar
      value: $[counter(variables['patch'], 1)]
  steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '3.x'
        installationPath: $(Agent.ToolsDirectory)/dotnet

    - script: dotnet tool install --global GitVersion.Tool
      displayName: 'Install GitVersion'

    - script: gitversion /updateassemblyinfo
      displayName: 'Update Version'

  next-version: $(counterVar).0
mode: Mainline
legacy-semver-padding: 0
build-metadata-padding: 0
commits-since-version-source-padding: 0
assembly-versioning-scheme: MajorMinorPatch
assembly-file-versioning-scheme: MajorMinorPatchTag
assembly-informational-format: '{LegacySemVer}'
branches:
  main:
    regex: main
    increment: Patch
    prevent-increment-of-merged-branch-version: true
    tag: ''
    track-merge-target: false
    tracks-release-branches: false
    is-release-branch: false
  release:
    regex: ^dev(elop)?(ment)?$
    source-branches: ['main']
    increment: Patch
    prevent-increment-of-merged-branch-version: true
    tag: beta
    track-merge-target: false
    tracks-release-branches: false
    is-release-branch:  true
