parameters:
  TargetProjects: 'src/**/*.csproj'
  
jobs:
- job: CodeBuild
  pool:
    name: SLD Build pool
  variables:
  - group: BUILD Management Resources
  - name: SolutionBaseName
    value: SFA.DAS.Payments.Application
  steps:
  - template: /azure-pipelines-templates/build/step/gitversion.yml

  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: ${{ parameters.TargetProjects }}
      noCache: true
      feedsToUse: 'select'
      vstsFeed: 'dct-pkg'
      includeNuGetOrg: true

  - task: NuGetCommand@2
    displayName: Restore
    inputs:
      command: restore
      projects: ${{ parameters.TargetProjects }}
      noCache: true
      feedsToUse: 'select'
      vstsFeed: 'dct-pkg'
      includeNuGetOrg: true
    
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      projects:  ${{ parameters.TargetProjects }}
      arguments: '--configuration $(buildConfiguration) --no-restore'

  - template: /azure-pipelines-templates/build/step/nuget-pack.yml
    parameters:
      DotNetStandardPackagesToPack: |
        src/SFA.DAS.Payments.Messages.Core/SFA.DAS.Payments.Messages.Core.csproj;
        src/SFA.DAS.Payments.Application/SFA.DAS.Payments.Application.csproj;
        src/SFA.DAS.Payments.Core/SFA.DAS.Payments.Core.csproj;
        src/SFA.DAS.Payments.Messaging/SFA.DAS.Payments.Messaging.csproj;
        src/SFA.DAS.Payments.Model.Core/SFA.DAS.Payments.Model.Core.csproj;
        